version: '2'
services:

  notebook:
    image: "jupyter/all-spark-notebook"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/bdge
    user: root
    environment:
      - NB_UID=1001
      - GRANT_SUDO=yes
    depends_on:
      - neo4j

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
