version: '2'
services:
  notebook:
    image: "jupyter/all-spark-notebook"
    ports:
      - "8888:8888"
    user: root
    environment:
      - NB_UID=1001
      - GRANT_SUDO=yes
    volumes:
      - ..:/home/jovyan/bdge
