version: '2'
services:

  notebook:
    image: "jupyter/all-spark-notebook"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/bdge
    user: root
    environment:
      - NB_UID=1001
      - GRANT_SUDO=yes
    depends_on:
      - mongo 

  mongo:
    image: mongo
    ports:
      - 27017 

