version: '2'
services:

  notebook:
    image: "jupyter/scipy-notebook"
    ports:
      - "8888:8888"
    volumes:
      - ..:/home/jovyan/bdge
    user: root
    environment:
      - NB_UID=1001
      - GRANT_SUDO=yes
    command: start-notebook.sh --NotebookApp.token=''
    depends_on:
      - mongo 

  mongo:
    image: mongo
    ports:
      - 27017 

